### ISSUE TITLE
pendulum and Flask-Session should be pinned in v2.6.3

### ISSUE THREAD

**Issue by ababino** [micael-grilo/airflow-dags-test-action#8]
Hi! I'm using v2.6.3 of this action, and it has been failing because pendulum and Flask-Session released non-backward compatible versions.  I really want to help fix this issue, but I am unable to open a pull request because the fix involves amending an old commit and changing the v2.6.3 tag to point to the updated file. However, I did manage to fix the problem in my forked repository, and it seems to be working perfectly fine now. Here's what I did to fix it:
```bash
git checkout v2.6.3
git branch pin-requirements
git checkout pin-requirements
```
Insert these in lines 3 and 4 of the Dockerfile
```
RUN pip install 'pendulum<3.0.0'
RUN pip install Flask-Session==0.5.0 
```
Commit, update, and push the tag
```
git tag -f v2.6.3 commit-hash
git push --force origin v2.6.3
```
I hope this is useful

**Comment by micael-grilo** [comment]
Thanks @ababino just updated the v2.6.3 tag and the package.
